---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: secret
data:
  CLOUDINARY_CLOUD_NAME: ZHE1ajhmNGRy
  CLOUDINARY_KEY: NTM3MzU1NTM2Nzk0MTQz 
  CLOUDINARY_SECRET: MDdTZ3ZpekJfaUtWbVozeFZIMjg3bVZxbEg0
  MAPBOX_TOKEN: cGs uZXlKMU lqb2l aV05tWlhO dFpYWXl MQ0po SWpv aVkybjlP WEU2Wl hBOU 1HeGx NVEptYzJ oc WR6Qn ZjbTVz Tmkjel5FVC1BRk JRV1Nk UXY4Rl9 VQT BmYnln
  DB_URL: bW9uZ29kYitzcnY6Ly9lbW1hbnVlbHN0ZXZfZGJfdXNlcjo5cVVRRGFrYWZBUXJiTHNVQGRldm9wcy1wcm9qLnc yZWVlMHUubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUm dz1tYWpvcml0eSZhcHBOYW1lPURldm9wcy1wcm9q
  SECRET: ZGV2b3Bz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: emstev/camp:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
